config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  mount Sidekiq::Web, at: '/sidekiq'

  get "/auth/twitter", as: :sign_in_with_twitter
  get "/auth/twitter/callback" => "callbacks#index"

  resources :discussions do
    resources :comments, only: [:create]
  end
  resources :users, only: [:new, :create]

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :campaigns
    end
  end

  resources :nearby_campaigns, only: [:index]
  resources :campaigns do
    resources :publishings, only: [:create]
    resources :pledges, only: [:create]
    resources :comments, only: [:create]
  end

  resources :pledges, only: [] do
    resources :payments, only: [:new, :create]
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  root "campaigns#index"

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user

  def new
    @pledge = Pledge.find params[:pledge_id]
  end

  def create
    @pledge = Pledge.find params[:pledge_id]
    service = Payments::HandlePayment.new(pledge:       @pledge,
                                          stripe_token: params[:stripe_token],
                                          current_user: current_user)
    if service.call
      redirect_to @pledge.campaign, notice: "Thanks for the payment"
    else
      redirect_to new_pledge_payment_path(@pledge), alert: "Try again!"
    end
  end


end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/new.html.erb
<%= form_tag pledge_payments_path(@pledge), id: "submission-form" do %>
  <%= hidden_field_tag :stripe_token %>
<% end %>

<h1>Make a Payment</h1>
<div class="text-danger" id="stripe-error-message"></div>
<%= form_tag "", id: "stripe-form" do %>
  <div class="form-group">
    <label for="card-number">Card Number</label>
    <input type="text" class="form-control" id="card-number" data-stripe="number">
  </div>
  <div class="form-group">
    <div class="row">
      <div class="col-md-12">
        <%= label_tag :card_expiry %>
      </div>
      <div class="col-md-3">
        <%= select_month(Date.today, {add_month_numbers: true},
                                     {id: "card-month",
                                      class: "form-control",
                                      data: {stripe: "exp-month"}}) %>
      </div>
      <div class="col-md-3">
        <%= select_year(Date.today, {start_year: Time.now.year,
                                     end_year: Time.now.year + 7},
                                     {id: "card-year",
                                      class: "form-control",
                                      data: {stripe: "exp-year"}}) %>
      </div>
    </div>
    <div class="form-group">
      <%= label_tag :cvc %>
      <%= text_field_tag :cvc, "", class: "form-control", data: {stripe: "cvc"} %>
    </div>
    <%= submit_tag "Make a Payment", class: "btn btn-primary" %>
  </div>

<% end %>