config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  mount Sidekiq::Web, at: '/sidekiq'

  get "/auth/twitter", as: :sign_in_with_twitter
  get "/auth/twitter/callback" => "callbacks#index"

  resources :discussions do
    resources :comments, only: [:create]
  end
  resources :users, only: [:new, :create]

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :campaigns
    end
  end

  resources :nearby_campaigns, only: [:index]
  resources :campaigns do
    resources :publishings, only: [:create]
    resources :pledges, only: [:create]
    resources :comments, only: [:create]
  end

  resources :pledges, only: [] do
    resources :payments, only: [:new, :create]
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  root "campaigns#index"

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  belongs_to :user

  has_many :comments, as: :commentable

  has_many :pledges, dependent: :nullify
  has_many :pledged_users, through: :pledges, source: :user

  has_many :rewards, dependent: :destroy
  # this enables us to creates rewards at the time we create the campaign.
  # by passing in special key: rewards_attributes
  # reject_if: :all_blank will ignore all nested rewards if all the attributes
  # are blank
  accepts_nested_attributes_for :rewards, reject_if: :all_blank,
                                          allow_destroy: true

  validates :title, presence: true
  validates :goal, presence: true, numericality: {greater_than: 10}

  # this validation will ensure that the campaign has at least one reward
  validates :rewards, presence: {message: "must have at least 1 reward"}

  # we instruct geocoder about the field we would like it to geocode by. In
  # our case we only have a single database field called `address` so we can
  # just pass that in. If you had multiple fields to compose the address then
  # your can make a method that looks like:
  # def full_street_address
  #   "#{street_address} #{city} #{country} #{postal_code}"
  # end
  # then your line will be like:
  # geocoded_by :full_street_address
  geocoded_by :address

  # This will initiate the `gecode` method after it validates the record so
  # before saving you will have the `longitude` and `latitude`
  after_validation :geocode

  include AASM

  # we put all the states and transitions in the `aasm` block
  aasm whiny_transitions: false do
    state :draft, initial: true
    state :published
    state :funded
    state :unfunded
    state :closed

    event :publish do
      transitions from: :draft, to: :published
    end

    event :fund do
      transitions from: :published, to: :funded
    end

    event :unfund do
      transitions from: :published, to: :unfunded
    end

    event :close do
      transitions from: [:draft, :published], to: :closed
    end

  end

end

# c1 = Campaign.new(title: "Another campaign", description: "Another description", goal: 1000000,
# rewards_attributes: {"0" => {body: "Thank you", amount: 5}, "1" => {body: "Super Thank You", amount: 10} })

app/controllers/api/v1/campaigns_controller.rb
class Api::V1::CampaignsController < Api::BaseController

  def index
    @campaigns = Campaign.includes(:rewards).references(:rewards).
                          order(:created_at).decorate
    # render json: @campaigns, each_serializer: CampaignSerializer
  end

  def show
    campaign = Campaign.find params[:id]
    render json: campaign
  end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :authenticate_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :find_campaign, only: [:edit, :update, :destroy, :show]

  DEFAULT_REWARD_COUNT = 2

  def new
    @campaign = Campaign.new
    # DEFAULT_REWARD_COUNT.times { @campaign.rewards.build }
  end

  def create
    service = Campaigns::CreateCampaign.new(params: campaign_params,
                                            user:   current_user)
    if service.call
      redirect_to campaign_path(service.campaign)
    else
      @campaign = service.campaign
      number_to_build = DEFAULT_REWARD_COUNT - @campaign.rewards.size
      number_to_build.times { @campaign.rewards.build }
      render :new
    end
  end

  def show
    @comment = Comment.new
    @pledge  = Pledge.new
  end

  def edit
    if @campaign.user != current_user
      redirect_to root_path, alert: "Access denied!"
    end
  end

  def update
    if @campaign.user != current_user
      redirect_to root_path
    elsif @campaign.update campaign_params
      redirect_to campaign_path(@campaign)
    else
      render :edit
    end
  end

  def index
    @campaigns = Campaign.includes(:rewards).references(:rewards).order(:created_at)
    respond_to do |format|
      format.html { render }
      format.json { render json: @campaigns.to_json }
    end
  end

  def destroy
    if current_user == @campaign.user
      @campaign.destroy
      redirect_to campaigns_path
    else
      redirect_to root_path
    end
  end

  private

  def find_campaign
    # @campaign = @campaign.decorate
    @campaign = Campaign.find(params[:id]).decorate
  end

  def campaign_params
    params.require(:campaign).permit(:title, :goal, :description, :end_date,
                                      :address,
                                     rewards_attributes: [:amount, :body, :id,
                                                          :_destroy])
  end

end

app/helpers/api/v1/campaigns_helper.rb
module Api::V1::CampaignsHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
  def label_class(state)
    case state
    when "draft"
      "label-default"
    when "published"
      "label-primary"
    when "funded"
      "label-success"
    when "unfunded"
      "label-danger"
    when "closed"
      "label-warning"
    end
  end
end

app/views/campaigns/_form.html.erb
<%= simple_form_for @campaign do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :goal, as: :string %>
  <%= f.input :end_date %>
  <%= f.input :address %>
  <h2>Rewards</h2>
  <%= f.error :rewards %>
  <%= f.simple_fields_for :rewards do |r| %>
    <%= render "reward_fields", f: r %>
  <% end %>
  <div class="links">
    <%# link_to_add_association helped method comes from the Cocoon gem %>
    <%= link_to_add_association "Add Reward", f, :rewards  %>
  </div>
  <%= f.submit %>
<% end %>

app/views/campaigns/_reward_fields.html.erb
<div class="nested-fields">
  <%= f.input :body %>
  <%= f.input :amount, as: :string %>
  <%#= f.input :_destroy, as: :boolean %>
  <%= link_to_remove_association "remove reward", f %>
</div>

app/views/campaigns/edit.html.erb
<h1>Edit Campaign</h1>
<%= render "form" %>

app/views/campaigns/index.html.erb
<h1>Fund.sy - Your Awesome Crowdfunding Solution</h1>
<h2>Recent Campaigns</h2>
<% @campaigns.each do |campaign| %>
 <%# using `cache` helper method. Rails will generate a fragement cache for this
     template. If you pass it an ActiveRecord object (such as `campaign`) it
     will use `cache_key` method to generate the cache key %>
  <% cache campaign, expires_in: 1.days do %>
    <div class="well">
      <h3>
        <%= link_to campaign.title.upcase, campaign %>
        (<%= campaign.rewards.size %> rewards)
      </h3>
    </div>
  <% end %>
<% end %>

app/views/campaigns/new.html.erb
<h1>New Campaign</h1>
<%= render "form" %>

app/views/campaigns/show.html.erb
<h1><%= @campaign.title %></h1>
<p><%= @campaign.description %></p>
<p>Goal: <%= @campaign.goal %></p>
<p>End Date: <%= @campaign.end_date %></p>
<p><%= @campaign.state_label %></p>
<%# may_publish? is a method generated by AASM that will tell you if you're able
    to publish a campaign based on the rules defined in the Campaign AASM %>
<%= @campaign.publish_button %>

<%= link_to "Edit", edit_campaign_path(@campaign), class: "btn btn-info" %>
<%= link_to "Delete", @campaign, class: "btn btn-danger" %>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers([
      {
        "lat": <%= @campaign.latitude %>,
        "lng": <%= @campaign.longitude %>,
        "infowindow": "<%= @campaign.title %>"
      }
    ]);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

<hr>
<% @campaign.rewards.each do |reward| %>
  <div class="col-md-3 well">
    <%= number_to_currency(reward.amount) %>
    <p><%= reward.body %></p>
  </div>
<% end %>
<div class="clearfix"></div>
<hr>
<h2>Make a Pledge</h2>
<%= simple_form_for [@campaign, @pledge] do |f| %>
  <%= f.input :amount, as: :string %>
  <%= f.submit "Pledge", class: "btn btn-primary" %>
<% end %>

<hr>
<h2>Comments</h2>

<%= simple_form_for [@campaign, @comment] do |f| %>
  <%= f.input :body %>
  <%= f.submit %>
<% end %>

<% @campaign.comments.each do |com| %>
  <div class="well">
    <%= com.body %>
  </div>
<% end %>

app/views/campaigns/show.html.slim
h1= @campaign.title
p= @campaign.description
p 
  | Goal: #{number_to_currency(@campaign.goal)}
p
  | End Date: #{@campaign.end_date.strftime("%Y-%b-%d %H:%m")}
p
  span class="label #{label_class(@campaign.aasm_state) }"
    = @campaign.aasm_state.capitalize
-# may_publish? is a method generated by AASM that will tell you if you're able to publish a campaign based on the rules defined in the Campaign AASM
- if @campaign.may_publish?
  = link_to "Publish", campaign_publishings_path(@campaign),
              method: :post,
              data:   {confirm: "Are you sure you want to publish?"},
              class:  "btn btn-primary"

= link_to "Edit", edit_campaign_path(@campaign), class: "btn btn-info"
= link_to "Delete", @campaign, class: "btn btn-danger"
hr
- @campaign.rewards.each do |reward|
  .col-md-3.well#my-id
    = number_to_currency(reward.amount)
    p= reward.body

h2 
  | Comments

= simple_form_for [@campaign, @comment] do |f|
  = f.input :body
  = f.submit

- @campaign.comments.each do |com|
  .well= com.body