config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  mount Sidekiq::Web, at: '/sidekiq'

  get "/auth/twitter", as: :sign_in_with_twitter
  get "/auth/twitter/callback" => "callbacks#index"

  resources :discussions do
    resources :comments, only: [:create]
  end
  resources :users, only: [:new, :create]

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :campaigns
    end
  end

  resources :nearby_campaigns, only: [:index]
  resources :campaigns do
    resources :publishings, only: [:create]
    resources :pledges, only: [:create]
    resources :comments, only: [:create]
  end

  resources :pledges, only: [] do
    resources :payments, only: [:new, :create]
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  root "campaigns#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Welcome to Fund.sy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script>
  <script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  <meta name="stripe-pk" content="<%= Rails.application.secrets.stripe_publishable_key %>">

  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <nav>
      <%= link_to "Home", root_path %> |
      <%= link_to "Discussions", discussions_path %> |
      <%= link_to "New Campaign", new_campaign_path %> |
      <div class="pull-right">
        <% if user_signed_in? %>
          <%= current_user.full_name %>
          <%= link_to "Logout", sessions_path, method: :delete %>
        <% else %>
          <%= link_to "Sign In", new_session_path %>
          <%= link_to "Sign In With Twitter", sign_in_with_twitter_path %>
          <%= link_to "Sign Up", new_user_path %>
        <% end %>
      </div>
    </nav>
    <%#= flash || notice %>
    <% if flash[:notice] %>
      <div class="alert alert-success"><%= flash[:notice] %></div>
    <% elsif flash[:alert] %>
      <div class="alert alert-danger"><%= flash[:alert] %></div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>